### ISSUE TITLE
Abrupt Removal of Released Versions Affecting CI Pipelines

### ISSUE THREAD

**Issue by sadaf-behbahani** [segment-integrations/analytics-swift-live#16]
I’m reopening this discussion because the concerns raised in the previously closed issue [#15 ](https://github.com/segment-integrations/analytics-swift-live/issues/15)  were not adequately addressed, and the impact on dependent teams and projects remains unresolved.

The removal of released versions without proper deprecation is causing widespread build failures across CI pipelines. This isn’t a minor inconvenience—it affects entire companies relying on these libraries to maintain their production environments. Abrupt changes like this disrupt development workflows and can lead to significant delays and unplanned work.

Closing the issue without addressing these critical points doesn’t resolve the problem:

* There is no mitigation strategy provided for teams now dealing with broken builds.
* Companies depending on the removed versions have no clear path to move forward without immediate and potentially risky changes to their codebase.
* The lack of a deprecation window undermines confidence in the stability of this library.

I strongly urge the maintainers to:

* Reintroduce the removed versions (even temporarily) as deprecated releases to give teams time to transition.
* Clearly communicate a timeline for the removal of deprecated versions, allowing developers to plan accordingly.
* Share actionable guidance for resolving dependencies to newer versions, if available.

Closing this issue without implementing a solution effectively leaves a major gap in support and reliability for this project. I hope the severity of the situation is reconsidered, and a resolution can be prioritized.

Looking forward to your response.

Best regards,
Sadaf

**Comment by bsneed** [comment]
Please refer to conversation in #15
