### ISSUE TITLE
Using `git@` rather than `https://` reference in Package.swift breaks Xcode

### ISSUE THREAD

**Issue by stephengilroy-grx** [segment-integrations/analytics-swift-live#4]
Hey @bsneed!

I'm integrating this framework (via https://github.com/segment-integrations/analytics-swift-filters.git) into our iOS app right now and I've noticed an issue with how Segment has set up the `Package.swift` files. By using the SSH protocol (aka `git@`) rather than `https://` for the dependencies a number of issues begin to occur within SPM and Xcode. 

https://github.com/segment-integrations/analytics-swift-live/blob/main/Package.swift#L22-L23

This is due to a bug within SPM that causes a dangling ref in git when using SSH. I did a ton of digging in our own project a while back and detailed my finding here as well as raised a bug with Apple: https://stackoverflow.com/a/72905516/6519068

Would it be possible to move these over to the `https` references? Right now this is a blocker for us as it basically makes our project unusable for our team. 

I'll be making a similar issue over on the `analytics-swift-filters` repo for posterity sake.

Thanks!

**Comment by bsneed** [comment]
Hi Stephen!  Absolutely!  Thanks for sharing that background.  I'll get this on my plate for today.

**Comment by stephengilroy-grx** [comment]
Amazing! Really appreciate the quick turnaround 💪

**Comment by bsneed** [comment]
Fixed in 0.2.4.  Thanks Stephen!
